### ISSUE TITLE
[Help] How to subscribe queue group with Nestjs decorator @MessagePattern?

### ISSUE THREAD

**Issue by kuccilim** [nestjs-ex/stan-strategy#1]
Hi, need help on STAN queue group, does this microservice strategy support Nestjs decorator like `MessagePattern` or `EventPattern` ?

**Comment by panoti** [comment]
Yeah, I re-use redis, mqtt strategy for MessagePattern. EventPattern is obviously supported.

**Comment by kuccilim** [comment]
Thanks, I had successfully connect to stan server, however, it seems like using `@MessagePattern('user_created')` was unable to pass in subscriptions options such as `DurableName, SetManualAckMode`.

**Comment by panoti** [comment]
I hope version 7.1.0 will help you. I have just added `subscribe` option when you init new strategy.
```typescript
{
        ...
        subscribe: { // [optional]
              durableName: 'durable', // [optional] the real name is <durableName>-<channel>
              manualAcks: false // [optional]
        }
}
```

**Comment by kuccilim** [comment]
The subscribe options are working, thanks alot.

I found a bug using StanContext will cause first argument become undefined.

```ts
  @MessagePattern('test')
  onTestMessage(data /* <= this will become undefined */, @Ctx() context: StanContext): any {
   // code logic
  }
```
